### ISSUE TITLE
serve.py 동작 가능하도록 처리

### ISSUE THREAD

**Issue by mukaman84** [pajamacoders/ocrDeskew#1]
1. serve.py로 batch 1 inference할 경우 "batchnorm1d, "inference", expected more than 1 value per channel when training, got input size"
오류 발생함, inference할 때 batchnorm1d을 주석처리하면 결과가 제대로 나오지않음

2. 단, test를  test_file내 'account1_10.png', 'account1_30.png'를 사용해서 하였기에 결과가 제대로 안나오는것이 테스트 데이터 문제인지는알수 없음'

3. 'account1_10.png'은 조금 이상해서 'account1_30.png'이나 기존데이터로 serve.py로 정상 inference나오도록 작업 요청

**Comment by pajamacoders** [comment]
devStream_fft 에 serve.py 추가 및 테스트 완료
1.serve.py로 batch 1 inference할 경우 "batchnorm1d, "inference", expected more than 1 value per channel when training, got input size" 오류 발생함, inference할 때 batchnorm1d을 주석처리하면 결과가 제대로 나오지않음
**_-> Answer: model을 eval 모드로 변경 하면 해당 에러는 없어 집니다._**
2. 단, test를 test_file내 'account1_10.png', 'account1_30.png'를 사용해서 하였기에 결과가 제대로 안나오는것이 테스트 데이터 문제인지는알수 없음'
**_->Answer: demo_result 폴더에 inference 결과 시각화 해 저장했습니다. 각 이미지의 왼쪽은 모델 입력으로 들어간 rotation 발생한 이미지, 오른쪽은 inference된 결과로 rotation correction 한 이미지입니다._**
3. 'account1_10.png'은 조금 이상해서 'account1_30.png'이나 기존데이터로 serve.py로 정상 inference나오도록 작업 요청
**_->Answer: 현재 테스트 이미지는 정상적으로 inference되는 것은 보이나 다음과 같은 경우 inference가 매우 부정확 해 지는 경향이 있습니다._**
 
inference가 부정확 해 지는 경우 :

1. 문서의 내용 보다 배경의 복잡도가 더 높은 경우(예: 카메라로 민증을 찍었는데 배경이 solid 한 색상이 아닌 패턴이 있는 경우)
2. 단순 rotation 이 아니라 Dof 2 이상의 3D 공간 상에서 회전이 발생한 경우(예: 카메라로 여권, 민증 등을 촬영할 경우)
3. 문서 내 글자보다 더 강한  에지(이미지의 경계선 등)가 문서 내용 회전 방향과 관계 없는 방향으로 발생한 경우
